# Generated by Django 4.1.3 on 2022-11-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='roll',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='sub',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
